version: '3.5'
services:
  web-app:
    image: tomcat:10.0-jdk17
    ports:
      - "8888:8080"
      - "5005:5005"
    command: "catalina.sh run"
    volumes:
      - "./target:/usr/local/tomcat/webapps"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    networks:
      - app-network

  pgsql:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db.currency_exchange
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pg.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge